from __future__ import annotations

from html import escape


def login_page(message: str | None = None, status_code: int = 200) -> tuple[str, int]:
    notice = f'<p class="error">{escape(message)}</p>' if message else ""
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Dashboard</title><style>
body{{font:16px system-ui,sans-serif;background:#f4f6f8;color:#17202a;margin:0}}main{{max-width:420px;margin:12vh auto;padding:24px;background:#fff;border:1px solid #dbe1e7;border-radius:8px}}label{{display:grid;gap:8px}}input,button{{font:inherit;padding:10px;border:1px solid #c8d0d8;border-radius:5px}}button{{margin-top:16px;background:#176b5b;color:#fff;cursor:pointer}}.error{{color:#a33a2b}}
</style></head><body><main><h1>Admin Dashboard</h1>{notice}<form method="post" action="/admin/login"><label>Password<input name="password" type="password" autocomplete="current-password"></label><button type="submit">Log in</button></form></main></body></html>''', status_code


def dashboard_page() -> str:
    return r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin dashboard</title><style>
:root{font:14px system-ui,sans-serif;color:#17202a;background:#f4f6f8}*{box-sizing:border-box}body{margin:0}.shell{max-width:1240px;margin:auto;padding:20px 16px 40px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:16px}.top h1{margin:0;font-size:24px}.actions,.buttons{display:flex;gap:8px;flex-wrap:wrap}button,input{font:inherit}button{border:1px solid #c8d0d8;border-radius:5px;background:#fff;padding:8px 11px;cursor:pointer}button.primary{background:#176b5b;border-color:#176b5b;color:#fff}button.danger{color:#a33a2b}button:disabled{opacity:.55;cursor:wait}.band,.panel{background:#fff;border:1px solid #dbe1e7;border-radius:8px;padding:14px;margin-bottom:16px}.status{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.status div{padding:10px;background:#f8fafb;border-left:3px solid #176b5b}.status b,.status span{display:block}.status span{color:#637181;font-size:12px;margin-bottom:4px}.grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(280px,1fr);gap:16px}.panel h2{font-size:17px;margin:0 0 12px}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-top:1px solid #e5e9ee;padding:9px 6px;vertical-align:top}th{font-size:12px;color:#637181}td{overflow-wrap:anywhere}.scroll{overflow:auto}form.inline{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.message{min-height:20px;color:#637181}.error{color:#a33a2b}.success{color:#176b5b}.muted{color:#637181;font-size:12px}@media(max-width:760px){.top{align-items:stretch;flex-direction:column}.status{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}@media(max-width:380px){.shell{padding:12px 10px}.status{grid-template-columns:1fr}}
</style></head><body><main class="shell" data-admin-dashboard>
<header class="top"><div><h1>Admin dashboard</h1><div class="muted">Last updated <span data-last-updated>never</span></div></div><div class="actions"><button type="button" data-refresh-button>Refresh</button><form method="post" action="/admin/logout"><button type="submit">Log out</button></form></div></header>
<section class="band" data-status-grid><div class="status"><div><span>Admin API</span><b data-admin-status>Checking</b></div><div><span>Storage</span><b data-upload-status>Checking</b></div><div><span>Knowledge</span><b data-knowledge-status data-repository-status>Checking</b></div><div><span>Documents</span><b data-document-count>0</b></div></div><p class="message" data-status-message></p></section>
<div class="grid"><section><div class="panel"><h2>Documents</h2><div class="scroll"><table data-document-table><thead><tr><th>Filename</th><th>Media</th><th>Original</th><th>Actions</th></tr></thead><tbody data-documents></tbody></table></div><p class="message" data-documents-message></p></div>
<div class="panel"><h2>Revisions</h2><div class="scroll"><table data-revision-table><thead><tr><th>Revision</th><th>Date</th><th>Changes</th><th></th></tr></thead><tbody data-revisions></tbody></table></div><p class="message" data-revisions-message></p></div></section>
<aside><div class="panel"><h2>Upload or rebuild</h2><form data-upload-form><label>Document file <input type="file" name="file" required accept=".pdf,.md,.tex,application/pdf,text/markdown,text/x-tex,application/x-tex"></label><div class="buttons"><button class="primary" type="submit">Upload</button><button type="button" data-rebuild>Rebuild</button></div></form><p class="message" data-upload-message></p></div>
<div class="panel"><h2>Backups</h2><div class="buttons"><button type="button" data-create-knowledge-backup>Create knowledge</button><button class="primary" type="button" data-create-full-backup>Create full</button></div><div class="scroll"><table><thead><tr><th>Name</th><th>Size</th><th></th></tr></thead><tbody data-backups></tbody></table></div><p class="message" data-backups-message></p></div>
<div class="panel"><h2>Restore</h2><form data-restore-form><input type="file" name="file" required accept=".bundle,.tar.gz,application/gzip,application/octet-stream"><button class="danger" type="submit">Restore backup</button></form><p class="message" data-restore-message></p></div></aside></div></main>
<script>
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const msg=(s,v,c='')=>{const e=$(s);if(e){e.textContent=v;e.className='message '+c}};
async function call(url,opt={}){const r=await fetch(url,{...opt,headers:{Accept:'application/json',...(opt.headers||{})}});if(!r.ok){if(r.status===401)location.href='/admin/login';throw new Error('Request could not be completed')}return r.json()}
async function load(){try{const [st,ds,rs,bs]=await Promise.all([call('/admin/ui/status'),call('/admin/ui/documents'),call('/admin/ui/revisions'),call('/admin/ui/backups')]);const k=st.knowledge||{},s=st.storage||{}; $('[data-admin-status]').textContent=st.admin?.enabled?'Enabled':'Disabled';$('[data-upload-status]').textContent=s.writable?'Writable':'Unavailable';$('[data-knowledge-status]').textContent=k.initialized?'Ready':'Empty';$('[data-document-count]').textContent=s.document_count??0;$('[data-last-updated]').textContent=new Date().toLocaleString();$('[data-documents]').innerHTML=(ds.documents||[]).map(d=>`<tr><td>${esc(d.original_filename)}</td><td>${esc(d.media_type)}</td><td>${d.original_available?'Available':'Missing'}</td><td><button type="button" data-replace="${esc(d.document_id)}">Replace</button> <button class="danger" type="button" data-delete="${esc(d.document_id)}">Delete</button></td></tr>`).join('');$('[data-revisions]').innerHTML=(rs.revisions||[]).map(x=>`<tr><td>${esc(x.commit?.slice(0,12))}</td><td>${esc(x.authored_at)}</td><td>${esc((x.changed_paths||[]).length)} file(s)</td><td><button type="button" data-rollback="${esc(x.commit)}">Rollback</button></td></tr>`).join('');$('[data-backups]').innerHTML=(bs.backups||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.size_bytes)} bytes</td><td><a href="/admin/ui/backups/${encodeURIComponent(x.name)}">Download</a> <button class="danger" type="button" data-backup-delete="${esc(x.name)}">Delete</button></td></tr>`).join('');}catch(e){msg('[data-status-message]',e.message,'error')}}
async function pending(button,fn){button.disabled=true;try{await fn();await load()}catch(e){msg('[data-status-message]',e.message,'error')}finally{button.disabled=false}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.delete&&confirm('Delete this document?'))pending(b,()=>call('/admin/ui/documents/'+b.dataset.delete,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true})}));if(b.dataset.rollback&&confirm('Rollback to this revision?'))pending(b,()=>call('/admin/ui/revisions/'+b.dataset.rollback+'/rollback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true})}));if(b.dataset.backupDelete&&confirm('Delete this backup?'))pending(b,()=>call('/admin/ui/backups/'+encodeURIComponent(b.dataset.backupDelete),{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true})}));if(b.dataset.replace){const i=document.createElement('input');i.type='file';i.onchange=()=>{const d=new FormData();d.append('file',i.files[0]);pending(b,()=>call('/admin/ui/documents/'+b.dataset.replace,{method:'PUT',body:d}))};i.click()}});
$('#refresh-button');$('[data-refresh-button]').onclick=load;$('[data-rebuild]').onclick=e=>pending(e.target,()=>call('/admin/ui/rebuild',{method:'POST'}));$('[data-create-knowledge-backup]').onclick=e=>pending(e.target,()=>call('/admin/ui/backups/knowledge',{method:'POST'}));$('[data-create-full-backup]').onclick=e=>pending(e.target,()=>call('/admin/ui/backups/full',{method:'POST'}));$('[data-upload-form]').onsubmit=e=>{e.preventDefault();const b=e.submitter,d=new FormData(e.target);pending(b,()=>call('/admin/ui/documents',{method:'POST',body:d}))};$('[data-restore-form]').onsubmit=e=>{e.preventDefault();if(!confirm('Restore this backup? Current data will be replaced.'))return;const b=e.submitter,d=new FormData(e.target);d.append('confirm','true');pending(b,()=>call('/admin/ui/restore',{method:'POST',body:d}))};load();setInterval(load,10000);
</script></body></html>'''
