from base64 import b64encode
from datetime import UTC, datetime
from hashlib import sha1
import json
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from banorte_agent.config import Settings


class GitHubAdminService:
    def __init__(self, settings: Settings, repo_root: Path | None = None) -> None:
        self.settings = settings
        self.repo_root = repo_root or Path.cwd()
        self.wiki_dir = Path(settings.wiki_dir)

    def status(self) -> dict[str, object]:
        if not self.settings.github_token:
            return {
                "configured": False,
                "connected": False,
                "base_branch": self.settings.github_base_branch,
                "pending_wiki_changes": False,
                "error": "GITHUB_TOKEN is not configured",
            }
        try:
            self._github_json("")
            pending = self.wiki_has_changes()
        except (HTTPError, URLError, OSError, RuntimeError) as exc:
            return {
                "configured": True,
                "connected": False,
                "base_branch": self.settings.github_base_branch,
                "pending_wiki_changes": False,
                "error": self._redact(str(exc)),
            }
        return {
            "configured": True,
            "connected": True,
            "base_branch": self.settings.github_base_branch,
            "pending_wiki_changes": pending,
            "error": None,
        }

    def wiki_has_changes(self) -> bool:
        if not self.settings.github_token:
            return False
        return bool(self.changed_wiki_files())

    def changed_wiki_files(self) -> list[str]:
        if not self.settings.github_token:
            raise RuntimeError("GITHUB_TOKEN is not configured")
        base = self._base_wiki_blobs()
        changed: list[str] = []
        for relative_path, data in self._local_wiki_files().items():
            repo_path = f"wiki/{relative_path}"
            if base.get(repo_path) != self.git_blob_sha(data):
                changed.append(repo_path)
        return sorted(changed)

    def publish(self) -> dict[str, object]:
        if not self.settings.github_token:
            raise RuntimeError("GITHUB_TOKEN is not configured")
        changed_files = self.changed_wiki_files()
        if not changed_files:
            return {"status": "noop", "changed_files": []}

        branch = f"wiki/upload-{_branch_suffix()}"
        base_ref = self._github_json(f"/git/ref/heads/{self.settings.github_base_branch}")
        base_sha = str(base_ref["object"]["sha"])
        base_commit = self._github_json(f"/git/commits/{base_sha}")
        base_tree_sha = str(base_commit["tree"]["sha"])
        tree = self._github_json(
            "/git/trees",
            data={"base_tree": base_tree_sha, "tree": self._tree_items(changed_files)},
        )
        commit = self._github_json(
            "/git/commits",
            data={
                "message": "docs: ingest uploaded wiki documents",
                "tree": tree["sha"],
                "parents": [base_sha],
                **self._commit_author_payload(),
            },
        )
        commit_sha = str(commit["sha"])
        self._github_json("/git/refs", data={"ref": f"refs/heads/{branch}", "sha": commit_sha})
        pr = self._create_pull_request(branch)
        return {
            "status": "ok",
            "branch": branch,
            "commit": commit_sha,
            "pull_request_url": pr.get("html_url"),
            "changed_files": changed_files,
        }

    def _create_pull_request(self, branch: str) -> dict[str, object]:
        return self._github_json(
            "/pulls",
            data={
                "title": "Ingest uploaded wiki documents",
                "head": branch,
                "base": self.settings.github_base_branch,
                "body": "Generated by the Banorte Agent admin publish endpoint.",
            },
        )

    def _base_wiki_blobs(self) -> dict[str, str]:
        ref = self._github_json(f"/git/ref/heads/{self.settings.github_base_branch}")
        commit = self._github_json(f"/git/commits/{ref['object']['sha']}")
        tree = self._github_json(f"/git/trees/{commit['tree']['sha']}?recursive=1")
        blobs: dict[str, str] = {}
        for item in tree.get("tree", []):
            if item.get("type") == "blob" and str(item.get("path", "")).startswith("wiki/"):
                blobs[str(item["path"])] = str(item["sha"])
        return blobs

    def _local_wiki_files(self) -> dict[str, bytes]:
        files: dict[str, bytes] = {}
        if not self.wiki_dir.exists():
            return files
        for path in sorted(self.wiki_dir.rglob("*")):
            if path.is_file():
                files[path.relative_to(self.wiki_dir).as_posix()] = path.read_bytes()
        return files

    def _tree_items(self, changed_files: list[str]) -> list[dict[str, object]]:
        local = self._local_wiki_files()
        items: list[dict[str, object]] = []
        for repo_path in changed_files:
            data = local[repo_path.removeprefix("wiki/")]
            blob = self._github_json(
                "/git/blobs",
                data={"content": b64encode(data).decode("ascii"), "encoding": "base64"},
            )
            items.append(
                {
                    "path": repo_path,
                    "mode": "100644",
                    "type": "blob",
                    "sha": blob["sha"],
                }
            )
        return items

    def _commit_author_payload(self) -> dict[str, dict[str, str]]:
        if not self.settings.github_commit_author_email:
            return {}
        return {
            "author": {
                "name": self.settings.github_commit_author_name,
                "email": self.settings.github_commit_author_email,
            }
        }

    def _github_json(
        self,
        path: str,
        data: dict[str, Any] | None = None,
        method: str | None = None,
    ) -> dict[str, object]:
        body = None if data is None else json.dumps(data).encode("utf-8")
        request = Request(
            f"https://api.github.com/repos/{self.settings.github_repository}{path}",
            data=body,
            headers={
                "Authorization": f"Bearer {self.settings.github_token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
                "Content-Type": "application/json",
            },
            method=method or ("GET" if data is None else "POST"),
        )
        with urlopen(request, timeout=5) as response:
            return json.loads(response.read().decode("utf-8"))

    def _redact(self, value: str) -> str:
        token = self.settings.github_token
        if token:
            value = value.replace(token, "[redacted]")
        return value

    @staticmethod
    def git_blob_sha(data: bytes) -> str:
        return sha1(f"blob {len(data)}\0".encode("utf-8") + data).hexdigest()


def _branch_suffix() -> str:
    return datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
